### ISSUE TITLE
Russian strings not recognized

### ISSUE THREAD

**Issue by usermode** [vdisasm/InnoSetupDecompiler#11]
; MessageBox example with russian characters.
	label_7282:
	v_1 := #65533#65533#65533#65533#65533#65533#65533#65533#65533' '#65533' '#65533#65533#65533#65533#65533#65533#65533#65533#65533#65533#65533#65533' '#65533#65533#65533#65533#65533' '#65533#65533#65533#65533#65533#65533#65533#65533#65533#65533'!'#13#13#65533#65533#65533#65533#65533#65533#65533#65533' '#65533#65533#65533#65533#65533#65533' '#65533#65533#65533#65533' '#65533#65533#65533' '#65533#65533#65533#65533#65533#65533#65533#65533' '#65533#65533#65533' '#65533#65533#65533#65533#65533'!';
	v_8 := 0;
	v_9 := 2;
	v_10 := v_1;
	v_7 := MSGBOX(v_10, v_9, v_8);
	result := 0;

**Comment by usermode** [comment]
I think the problem is solved in chars conversion in version 1.3.

**Comment by vdisasm** [comment]
It's addressed partially in 1.3. At least correct codes should be printed instead of #65533...  Better solution would be to introduce Code Page option for script.

**Comment by vdisasm** [comment]
Updated in internal release. Now we have project created for opened binary, which contains code page. All AnsiStrings are handled using code page.
